### ISSUE TITLE
[Backend] DB design for Video Conference Service

### ISSUE THREAD

**Issue by bubblemans** [bubblemans/2021-spring-cs160-team-EduAll#10]
- Support individual video rooms and password to join rooms

**Comment by aryanvaid2108** [comment]
Completed. 
[https://app.zenhub.com/files/335822753/f28c5abb-23d0-4228-ae20-2df49d8ceea4/download](https://app.zenhub.com/files/335822753/f28c5abb-23d0-4228-ae20-2df49d8ceea4/download)
